fs = require 'fs'

{print} = require 'sys'
{spawn} = require 'child_process'

watch = (output) ->
  coffee = spawn 'coffee', ['-w', '-c', '-o', output, 'source']
  coffee.stderr.on 'data', (data) ->
    process.stderr.write data.toString()
  coffee.stdout.on 'data', (data) ->
    print data.toString()

task 'watch', 'Watch source/ for changes', ->
    watch('build')
    watch('../examples/gae/showcase/static/js')
