fs = require 'fs'
util   = require 'util'

{print} = require 'sys'
{spawn} = require 'child_process'

outputDir = '../examples/gae/showcase/static/js'
filename = 'authomatic'

watchCoffee = (filename) ->
  coffee = spawn 'coffee', ['-w', '-m', '-c', "#{filename}.coffee"]
  coffee.stderr.on 'data', (data) ->
    process.stderr.write data.toString()
  coffee.stdout.on 'data', (data) ->
    print data.toString()

watchResult = (output)->
  for extension in ['coffee', 'js', 'map'] then do (extension) ->
    file = "#{filename}.#{extension}"
    fs.watchFile file, (curr, prev) ->
        if +curr.mtime isnt +prev.mtime
            util.log "Copying #{file} to #{outputDir}"
            fs.createReadStream(file).pipe(fs.createWriteStream("#{outputDir}/#{file}"))
            #invoke 'build'
  

task 'watch', 'Watch source/ for changes', ->
  watchResult(outputDir)
  watchCoffee(filename)
