application: authomatic-example
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico
  mime_type: image/x-icon
  
- url: /apple-touch-icon-precomposed.png
  static_files: static/img/apple-touch-icon-precomposed.png
  upload: static/img/apple-touch-icon-precomposed.png
  mime_type: image/png
  
- url: /google62b917dcf0f412c7.html
  static_files: static/google62b917dcf0f412c7.html
  upload: static/google62b917dcf0f412c7.html
  
- url: /static
  static_dir: static

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: "latest"

skip_files: |
  (config-template\.py)|
  (static/sass)|
  (static/\.sass-cache)|
  (.*\.rb)|
  (.*\.scssc)